server:
  port: 8084

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    instances:
      notification-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.kafka: INFO
