server:
  port: 8085

spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analytics-service-group
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

  datasource:
    url: jdbc:h2:mem:analyticsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.kafka: INFO
